/* 
 * =========================================================================
 * BUKU PINTAR PETA WILAYAH (RAJA ONGKIR DATA)
 * =========================================================================
 * File ini ibarat "Buku Atlas" raksasa yang berisi kamus data seluruh 
 * Provinsi dan Kabupaten/Kota di Indonesia.
 * 
 * Mengapa file ini diperlukan?
 * Agar saat Customer mengisi alamat pengiriman di form, mereka bisa tinggal 
 * pilih dari dropdown (tidak perlu mengetik manual). Data ID (angka) ini 
 * yang akan dikirim ke Backend untuk menghitung ongkos kirim (Ongkir).
 */

export const PROVINCES = [
  { province_id: 1, province: "NUSA TENGGARA BARAT (NTB)" },
  { province_id: 2, province: "MALUKU" },
  { province_id: 3, province: "KALIMANTAN SELATAN" },
  { province_id: 4, province: "KALIMANTAN TENGAH" },
  { province_id: 5, province: "JAWA BARAT" },
  { province_id: 6, province: "BENGKULU" },
  { province_id: 7, province: "KALIMANTAN TIMUR" },
  { province_id: 8, province: "KEPULAUAN RIAU" },
  { province_id: 9, province: "NANGGROE ACEH DARUSSALAM (NAD)" },
  { province_id: 10, province: "DKI JAKARTA" },
  { province_id: 11, province: "BANTEN" },
  { province_id: 12, province: "JAWA TENGAH" },
  { province_id: 13, province: "JAMBI" },
  { province_id: 14, province: "PAPUA" },
  { province_id: 15, province: "BALI" },
  { province_id: 16, province: "SUMATERA UTARA" },
  { province_id: 17, province: "GORONTALO" },
  { province_id: 18, province: "JAWA TIMUR" },
  { province_id: 19, province: "DI YOGYAKARTA" },
  { province_id: 20, province: "SULAWESI TENGGARA" },
  { province_id: 21, province: "NUSA TENGGARA TIMUR (NTT)" },
  { province_id: 22, province: "SULAWESI UTARA" },
  { province_id: 23, province: "SUMATERA BARAT" },
  { province_id: 24, province: "BANGKA BELITUNG" },
  { province_id: 25, province: "RIAU" },
  { province_id: 26, province: "SUMATERA SELATAN" },
  { province_id: 27, province: "SULAWESI TENGAH" },
  { province_id: 28, province: "KALIMANTAN BARAT" },
  { province_id: 29, province: "PAPUA BARAT" },
  { province_id: 30, province: "LAMPUNG" },
  { province_id: 31, province: "KALIMANTAN UTARA" },
  { province_id: 32, province: "MALUKU UTARA" },
  { province_id: 33, province: "SULAWESI SELATAN" },
  { province_id: 34, province: "SULAWESI BARAT" }
];

export const CITIES = {
  // Bengkulu (ID: 6)
  "6": [
    { city_id: 64, city_name: "BENGKULU", type: "Kota" },
    { city_id: 65, city_name: "BENGKULU UTARA", type: "Kota" },
    { city_id: 66, city_name: "BENGKULU TENGAH", type: "Kota" },
    { city_id: 67, city_name: "REJANG LEBONG", type: "Kota" },
    { city_id: 68, city_name: "BENGKULU SELATAN", type: "Kota" },
    { city_id: 69, city_name: "KAUR", type: "Kota" },
    { city_id: 70, city_name: "KEPAHIANG", type: "Kota" },
    { city_id: 71, city_name: "LEBONG", type: "Kota" },
    { city_id: 73, city_name: "MUKO MUKO", type: "Kota" },
    { city_id: 76, city_name: "SELUMA", type: "Kota" }
  ],
  // DI Yogyakarta (ID: 19)
  "19": [
    { city_id: 259, city_name: "YOGYAKARTA", type: "Kota" },
    { city_id: 260, city_name: "BANTUL", type: "Kota" },
    { city_id: 261, city_name: "SLEMAN", type: "Kota" },
    { city_id: 262, city_name: "KULON PROGO", type: "Kota" },
    { city_id: 263, city_name: "GUNUNG KIDUL", type: "Kota" }
  ],
  // Nanggroe Aceh Darussalam (NAD) (ID: 9) - dari data user yang berlabel "DKI Jakarta"
  "9": [
    { city_id: 97, city_name: "BANDA ACEH", type: "Kota" },
    { city_id: 98, city_name: "LANGSA", type: "Kota" },
    { city_id: 100, city_name: "LHOKSEUMAWE", type: "Kota" },
    { city_id: 101, city_name: "ACEH BESAR", type: "Kota" },
    { city_id: 102, city_name: "BIREUEN", type: "Kota" },
    { city_id: 104, city_name: "ACEH TENGGARA", type: "Kota" },
    { city_id: 106, city_name: "ACEH BARAT", type: "Kota" },
    { city_id: 107, city_name: "PIDIE", type: "Kota" },
    { city_id: 109, city_name: "ACEH TENGAH", type: "Kota" },
    { city_id: 110, city_name: "ACEH SELATAN", type: "Kota" },
    { city_id: 111, city_name: "SABANG", type: "Kota" },
    { city_id: 112, city_name: "ACEH BARAT DAYA", type: "Kota" },
    { city_id: 113, city_name: "ACEH JAYA", type: "Kota" },
    { city_id: 114, city_name: "ACEH SINGKIL", type: "Kota" },
    { city_id: 116, city_name: "ACEH TAMIANG", type: "Kota" },
    { city_id: 117, city_name: "ACEH TIMUR", type: "Kota" },
    { city_id: 118, city_name: "ACEH UTARA", type: "Kota" },
    { city_id: 120, city_name: "BENER MERIAH", type: "Kota" },
    { city_id: 122, city_name: "GAYO LUES", type: "Kota" },
    { city_id: 124, city_name: "NAGAN RAYA", type: "Kota" },
    { city_id: 125, city_name: "PIDIE JAYA", type: "Kota" },
    { city_id: 127, city_name: "SIMEULUE", type: "Kota" },
    { city_id: 128, city_name: "SUBULUSSALAM", type: "Kota" }
  ],
  // Gorontalo (ID: 17)
  "17": [
    { city_id: 251, city_name: "GORONTALO", type: "Kota" },
    { city_id: 252, city_name: "GORONTALO UTARA", type: "Kota" },
    { city_id: 253, city_name: "BOALEMO", type: "Kota" },
    { city_id: 254, city_name: "BONE BOLANGO", type: "Kota" },
    { city_id: 255, city_name: "POHUWATO", type: "Kota" }
  ],
  // Jambi (ID: 13)
  "13": [
    { city_id: 150, city_name: "JAMBI", type: "Kota" },
    { city_id: 152, city_name: "TANJUNG JABUNG BARAT", type: "Kota" },
    { city_id: 153, city_name: "MERANGIN", type: "Kota" },
    { city_id: 154, city_name: "BATANG HARI", type: "Kota" },
    { city_id: 156, city_name: "BUNGO", type: "Kota" },
    { city_id: 157, city_name: "SUNGAIPENUH", type: "Kota" },
    { city_id: 158, city_name: "KERINCI", type: "Kota" },
    { city_id: 160, city_name: "MUARO JAMBI", type: "Kota" },
    { city_id: 161, city_name: "SAROLANGUN", type: "Kota" },
    { city_id: 163, city_name: "TANJUNG JABUNG TIMUR", type: "Kota" },
    { city_id: 164, city_name: "TEBO", type: "Kota" }
  ],
  // Jawa Barat (ID: 5)
  "5": [
    { city_id: 55, city_name: "BANDUNG", type: "Kota" },
    { city_id: 56, city_name: "CIMAHI", type: "Kota" },
    { city_id: 57, city_name: "SUMEDANG", type: "Kota" },
    { city_id: 59, city_name: "GARUT", type: "Kota" },
    { city_id: 60, city_name: "BANDUNG BARAT", type: "Kota" },
    { city_id: 62, city_name: "CIANJUR", type: "Kota" },
    { city_id: 63, city_name: "BEKASI", type: "Kota" },
    { city_id: 77, city_name: "BOGOR", type: "Kota" },
    { city_id: 129, city_name: "CIREBON", type: "Kota" },
    { city_id: 131, city_name: "INDRAMAYU", type: "Kota" },
    { city_id: 132, city_name: "KUNINGAN", type: "Kota" },
    { city_id: 133, city_name: "MAJALENGKA", type: "Kota" },
    { city_id: 199, city_name: "DEPOK", type: "Kota" },
    { city_id: 329, city_name: "KARAWANG", type: "Kota" },
    { city_id: 532, city_name: "PURWAKARTA", type: "Kota" },
    { city_id: 533, city_name: "SUBANG", type: "Kota" },
    { city_id: 538, city_name: "SUKABUMI", type: "Kota" },
    { city_id: 632, city_name: "TASIKMALAYA", type: "Kota" },
    { city_id: 633, city_name: "BANJAR", type: "Kota" },
    { city_id: 634, city_name: "CIAMIS", type: "Kota" },
    { city_id: 635, city_name: "PANGANDARAN", type: "Kota" }
  ],
  // Jawa Tengah (ID: 12)
  "12": [
    { city_id: 149, city_name: "CILACAP", type: "Kota" },
    { city_id: 383, city_name: "MAGELANG", type: "Kota" },
    { city_id: 384, city_name: "KEBUMEN", type: "Kota" },
    { city_id: 385, city_name: "WONOSOBO", type: "Kota" },
    { city_id: 386, city_name: "PURWOREJO", type: "Kota" },
    { city_id: 387, city_name: "TEMANGGUNG", type: "Kota" },
    { city_id: 539, city_name: "SURAKARTA", type: "Kota" },
    { city_id: 540, city_name: "BOYOLALI", type: "Kota" },
    { city_id: 541, city_name: "KARANGANYAR", type: "Kota" },
    { city_id: 542, city_name: "KLATEN", type: "Kota" },
    { city_id: 543, city_name: "SRAGEN", type: "Kota" },
    { city_id: 544, city_name: "SUKOHARJO", type: "Kota" },
    { city_id: 545, city_name: "WONOGIRI", type: "Kota" },
    { city_id: 560, city_name: "SEMARANG", type: "Kota" },
    { city_id: 561, city_name: "JEPARA", type: "Kota" },
    { city_id: 562, city_name: "KUDUS", type: "Kota" },
    { city_id: 563, city_name: "PEKALONGAN", type: "Kota" },
    { city_id: 564, city_name: "BATANG", type: "Kota" },
    { city_id: 565, city_name: "BLORA", type: "Kota" },
    { city_id: 567, city_name: "DEMAK", type: "Kota" },
    { city_id: 568, city_name: "KENDAL", type: "Kota" },
    { city_id: 569, city_name: "PATI", type: "Kota" },
    { city_id: 570, city_name: "PEMALANG", type: "Kota" },
    { city_id: 571, city_name: "GROBOGAN", type: "Kota" },
    { city_id: 572, city_name: "REMBANG", type: "Kota" },
    { city_id: 573, city_name: "SALATIGA", type: "Kota" },
    { city_id: 575, city_name: "PURBALINGGA", type: "Kota" },
    { city_id: 576, city_name: "BANJARNEGARA", type: "Kota" },
    { city_id: 588, city_name: "TEGAL", type: "Kota" },
    { city_id: 589, city_name: "BREBES", type: "Kota" },
    { city_id: 591, city_name: "BANYUMAS", type: "Kota" }
  ],
  // Bali (ID: 15)
  "15": [
    { city_id: 201, city_name: "DENPASAR", type: "Kota" },
    { city_id: 203, city_name: "KARANGASEM", type: "Kota" },
    { city_id: 204, city_name: "BANGLI", type: "Kota" },
    { city_id: 205, city_name: "GIANYAR", type: "Kota" },
    { city_id: 206, city_name: "JEMBRANA", type: "Kota" },
    { city_id: 208, city_name: "KLUNGKUNG", type: "Kota" },
    { city_id: 210, city_name: "BULELENG", type: "Kota" },
    { city_id: 211, city_name: "TABANAN", type: "Kota" },
    { city_id: 212, city_name: "BADUNG", type: "Kota" }
  ],
  // Bangka Belitung (ID: 24)
  "24": [
    { city_id: 428, city_name: "PANGKAL PINANG", type: "Kota" },
    { city_id: 429, city_name: "BANGKA", type: "Kota" },
    { city_id: 430, city_name: "BANGKA BARAT", type: "Kota" },
    { city_id: 431, city_name: "BANGKA TENGAH", type: "Kota" },
    { city_id: 432, city_name: "BANGKA SELATAN", type: "Kota" },
    { city_id: 596, city_name: "BELITUNG", type: "Kota" },
    { city_id: 597, city_name: "BELITUNG TIMUR", type: "Kota" }
  ],
  // Banten (ID: 11)
  "11": [
    { city_id: 143, city_name: "CILEGON", type: "Kota" },
    { city_id: 144, city_name: "PANDEGLANG", type: "Kota" },
    { city_id: 147, city_name: "LEBAK", type: "Kota" },
    { city_id: 148, city_name: "SERANG", type: "Kota" },
    { city_id: 592, city_name: "TANGERANG", type: "Kota" },
    { city_id: 594, city_name: "TANGERANG SELATAN", type: "Kota" }
  ],
  // Jawa Timur (ID: 18)
  "18": [
    { city_id: 256, city_name: "JEMBER", type: "Kota" },
    { city_id: 257, city_name: "BANYUWANGI", type: "Kota" },
    { city_id: 258, city_name: "BONDOWOSO", type: "Kota" },
    { city_id: 289, city_name: "KEDIRI", type: "Kota" },
    { city_id: 353, city_name: "MADIUN", type: "Kota" },
    { city_id: 355, city_name: "MAGETAN", type: "Kota" },
    { city_id: 357, city_name: "NGAWI", type: "Kota" },
    { city_id: 359, city_name: "PACITAN", type: "Kota" },
    { city_id: 360, city_name: "PONOROGO", type: "Kota" },
    { city_id: 388, city_name: "MOJOKERTO", type: "Kota" },
    { city_id: 389, city_name: "JOMBANG", type: "Kota" },
    { city_id: 390, city_name: "NGANJUK", type: "Kota" },
    { city_id: 391, city_name: "MALANG", type: "Kota" },
    { city_id: 392, city_name: "BLITAR", type: "Kota" },
    { city_id: 393, city_name: "BATU", type: "Kota" },
    { city_id: 394, city_name: "PROBOLINGGO", type: "Kota" },
    { city_id: 395, city_name: "LUMAJANG", type: "Kota" },
    { city_id: 396, city_name: "SITUBONDO", type: "Kota" },
    { city_id: 531, city_name: "PASURUAN", type: "Kota" },
    { city_id: 566, city_name: "BOJONEGORO", type: "Kota" },
    { city_id: 577, city_name: "SURABAYA", type: "Kota" },
    { city_id: 578, city_name: "GRESIK", type: "Kota" },
    { city_id: 579, city_name: "LAMONGAN", type: "Kota" },
    { city_id: 580, city_name: "BANGKALAN", type: "Kota" },
    { city_id: 581, city_name: "PAMEKASAN", type: "Kota" },
    { city_id: 582, city_name: "SAMPANG", type: "Kota" },
    { city_id: 583, city_name: "SIDOARJO", type: "Kota" },
    { city_id: 584, city_name: "SUMENEP", type: "Kota" },
    { city_id: 585, city_name: "TUBAN", type: "Kota" },
    { city_id: 586, city_name: "TULUNGAGUNG", type: "Kota" },
    { city_id: 587, city_name: "TRENGGALEK", type: "Kota" }
  ],
  // Kalimantan Selatan (ID: 3)
  "3": [
    { city_id: 29, city_name: "BANJARMASIN", type: "Kota" },
    { city_id: 30, city_name: "HULU SUNGAI TENGAH", type: "Kota" },
    { city_id: 32, city_name: "HULU SUNGAI SELATAN", type: "Kota" },
    { city_id: 34, city_name: "KOTABARU", type: "Kota" },
    { city_id: 35, city_name: "TABALONG", type: "Kota" },
    { city_id: 36, city_name: "BANJARBARU", type: "Kota" },
    { city_id: 38, city_name: "HULU SUNGAI UTARA", type: "Kota" },
    { city_id: 39, city_name: "BARITO KUALA", type: "Kota" },
    { city_id: 40, city_name: "BANJAR", type: "Kota" },
    { city_id: 42, city_name: "TANAH LAUT", type: "Kota" },
    { city_id: 44, city_name: "TAPIN", type: "Kota" },
    { city_id: 53, city_name: "BALANGAN", type: "Kota" },
    { city_id: 54, city_name: "TANAH BUMBU", type: "Kota" }
  ],
  // Kalimantan Tengah (ID: 4)
  "4": [
    { city_id: 46, city_name: "BARITO UTARA", type: "Kota" },
    { city_id: 48, city_name: "BARITO TIMUR", type: "Kota" },
    { city_id: 50, city_name: "MURUNG RAYA", type: "Kota" },
    { city_id: 52, city_name: "BARITO SELATAN", type: "Kota" },
    { city_id: 456, city_name: "PALANGKA RAYA", type: "Kota" },
    { city_id: 458, city_name: "KATINGAN", type: "Kota" },
    { city_id: 460, city_name: "KAPUAS", type: "Kota" },
    { city_id: 462, city_name: "GUNUNG MAS", type: "Kota" },
    { city_id: 464, city_name: "SERUYAN", type: "Kota" },
    { city_id: 466, city_name: "KOTAWARINGIN BARAT", type: "Kota" },
    { city_id: 468, city_name: "KOTAWARINGIN TIMUR", type: "Kota" },
    { city_id: 470, city_name: "LAMANDAU", type: "Kota" },
    { city_id: 471, city_name: "PULANG PISAU", type: "Kota" },
    { city_id: 472, city_name: "SUKAMARA", type: "Kota" }
  ],
  // Kalimantan Timur (ID: 7)
  "7": [
    { city_id: 78, city_name: "BALIKPAPAN", type: "Kota" },
    { city_id: 79, city_name: "KUTAI KARTANEGARA", type: "Kota" },
    { city_id: 80, city_name: "PASER", type: "Kota" },
    { city_id: 81, city_name: "BERAU", type: "Kota" },
    { city_id: 83, city_name: "PENAJAM PASER UTARA", type: "Kota" },
    { city_id: 84, city_name: "BONTANG", type: "Kota" },
    { city_id: 86, city_name: "KUTAI TIMUR", type: "Kota" },
    { city_id: 534, city_name: "SAMARINDA", type: "Kota" },
    { city_id: 536, city_name: "KUTAI BARAT", type: "Kota" },
    { city_id: 537, city_name: "MAHAKAM ULU", type: "Kota" }
  ],
  // Kepulauan Riau (ID: 8)
  "8": [
    { city_id: 90, city_name: "BATAM", type: "Kota" },
    { city_id: 92, city_name: "LINGGA", type: "Kota" },
    { city_id: 94, city_name: "NATUNA", type: "Kota" },
    { city_id: 95, city_name: "KEPULAUAN ANAMBAS", type: "Kota" },
    { city_id: 96, city_name: "KARIMUN", type: "Kota" },
    { city_id: 619, city_name: "TANJUNG PINANG", type: "Kota" },
    { city_id: 624, city_name: "BINTAN", type: "Kota" }
  ],
  // Maluku (ID: 2)
  "2": [
    { city_id: 11, city_name: "AMBON", type: "Kota" },
    { city_id: 12, city_name: "MALUKU TENGAH", type: "Kota" },
    { city_id: 14, city_name: "MALUKU TENGGARA", type: "Kota" },
    { city_id: 15, city_name: "TUAL", type: "Kota" },
    { city_id: 16, city_name: "BURU", type: "Kota" },
    { city_id: 17, city_name: "BURU SELATAN", type: "Kota" },
    { city_id: 19, city_name: "KEPULAUAN ARU", type: "Kota" },
    { city_id: 21, city_name: "SERAM BAGIAN BARAT", type: "Kota" },
    { city_id: 23, city_name: "SERAM BAGIAN TIMUR", type: "Kota" },
    { city_id: 24, city_name: "MALUKU BARAT DAYA", type: "Kota" },
    { city_id: 25, city_name: "MALUKU TENGGARA BARAT", type: "Kota" }
  ],
  // Nusa Tenggara Barat (ID: 1)
  "1": [
    { city_id: 1, city_name: "MATARAM", type: "Kota" },
    { city_id: 2, city_name: "BIMA", type: "Kota" },
    { city_id: 3, city_name: "DOMPU", type: "Kota" },
    { city_id: 4, city_name: "LOMBOK TENGAH", type: "Kota" },
    { city_id: 5, city_name: "LOMBOK TIMUR", type: "Kota" },
    { city_id: 7, city_name: "SUMBAWA", type: "Kota" },
    { city_id: 8, city_name: "LOMBOK BARAT", type: "Kota" },
    { city_id: 9, city_name: "LOMBOK UTARA", type: "Kota" },
    { city_id: 10, city_name: "SUMBAWA BARAT", type: "Kota" }
  ],
  // Nusa Tenggara Timur (ID: 21)
  "21": [
    { city_id: 290, city_name: "KUPANG", type: "Kota" },
    { city_id: 292, city_name: "SUMBA TENGAH", type: "Kota" },
    { city_id: 293, city_name: "BELU", type: "Kota" },
    { city_id: 294, city_name: "MALAKA", type: "Kota" },
    { city_id: 296, city_name: "ALOR", type: "Kota" },
    { city_id: 297, city_name: "TIMOR TENGAH UTARA", type: "Kota" },
    { city_id: 298, city_name: "FLORES TIMUR", type: "Kota" },
    { city_id: 300, city_name: "SIKKA", type: "Kota" },
    { city_id: 301, city_name: "MANGGARAI", type: "Kota" },
    { city_id: 308, city_name: "TIMOR TENGAH SELATAN", type: "Kota" },
    { city_id: 309, city_name: "ENDE", type: "Kota" },
    { city_id: 310, city_name: "NGADA", type: "Kota" },
    { city_id: 313, city_name: "SUMBA TIMUR", type: "Kota" },
    { city_id: 314, city_name: "SUMBA BARAT", type: "Kota" },
    { city_id: 318, city_name: "MANGGARAI BARAT", type: "Kota" },
    { city_id: 319, city_name: "MANGGARAI TIMUR", type: "Kota" },
    { city_id: 321, city_name: "NAGEKEO", type: "Kota" },
    { city_id: 323, city_name: "ROTE NDAO", type: "Kota" },
    { city_id: 325, city_name: "SUMBA BARAT DAYA", type: "Kota" },
    { city_id: 326, city_name: "LEMBATA", type: "Kota" },
    { city_id: 328, city_name: "SABU RAIJUA", type: "Kota" }
  ],
  // Papua (ID: 14)
  "14": [
    { city_id: 165, city_name: "JAYAPURA", type: "Kota" },
    { city_id: 166, city_name: "BIAK NUMFOR", type: "Kota" },
    { city_id: 167, city_name: "MERAUKE", type: "Kota" },
    { city_id: 168, city_name: "NABIRE", type: "Kota" },
    { city_id: 169, city_name: "DOGIYAI", type: "Kota" },
    { city_id: 171, city_name: "KEPULAUAN YAPEN", type: "Kota" },
    { city_id: 172, city_name: "JAYAWIJAYA", type: "Kota" },
    { city_id: 174, city_name: "LANNY JAYA", type: "Kota" },
    { city_id: 175, city_name: "YALIMO", type: "Kota" },
    { city_id: 176, city_name: "NDUGA", type: "Kota" },
    { city_id: 177, city_name: "MAMBERAMO TENGAH", type: "Kota" },
    { city_id: 178, city_name: "ASMAT", type: "Kota" },
    { city_id: 180, city_name: "BOVEN DIGOEL", type: "Kota" },
    { city_id: 181, city_name: "KEEROM", type: "Kota" },
    { city_id: 183, city_name: "MAPPI", type: "Kota" },
    { city_id: 184, city_name: "INTAN JAYA", type: "Kota" },
    { city_id: 185, city_name: "PANIAI", type: "Kota" },
    { city_id: 186, city_name: "DEIYAI", type: "Kota" },
    { city_id: 187, city_name: "PEGUNUNGAN BINTANG", type: "Kota" },
    { city_id: 188, city_name: "PUNCAK JAYA", type: "Kota" },
    { city_id: 189, city_name: "PUNCAK", type: "Kota" },
    { city_id: 190, city_name: "SARMI", type: "Kota" },
    { city_id: 192, city_name: "SUPIORI", type: "Kota" },
    { city_id: 193, city_name: "TOLIKARA", type: "Kota" },
    { city_id: 195, city_name: "WAROPEN", type: "Kota" },
    { city_id: 196, city_name: "YAHUKIMO", type: "Kota" },
    { city_id: 198, city_name: "MAMBERAMO RAYA", type: "Kota" },
    { city_id: 595, city_name: "MIMIKA", type: "Kota" }
  ],
  // Riau (ID: 25)
  "25": [
    { city_id: 433, city_name: "PEKANBARU", type: "Kota" },
    { city_id: 434, city_name: "DUMAI", type: "Kota" },
    { city_id: 435, city_name: "KAMPAR", type: "Kota" },
    { city_id: 436, city_name: "BENGKALIS", type: "Kota" },
    { city_id: 438, city_name: "INDRAGIRI HULU", type: "Kota" },
    { city_id: 439, city_name: "INDRAGIRI HILIR", type: "Kota" },
    { city_id: 441, city_name: "ROKAN HILIR", type: "Kota" },
    { city_id: 443, city_name: "KUANTAN SINGINGI", type: "Kota" },
    { city_id: 444, city_name: "PELALAWAN", type: "Kota" },
    { city_id: 447, city_name: "ROKAN HULU", type: "Kota" },
    { city_id: 451, city_name: "SIAK", type: "Kota" },
    { city_id: 454, city_name: "KEPULAUAN MERANTI", type: "Kota" }
  ],
  // Sulawesi Barat (ID: 34)
  "34": [
    { city_id: 657, city_name: "MAMUJU", type: "Kota" },
    { city_id: 658, city_name: "MAMUJU TENGAH", type: "Kota" },
    { city_id: 662, city_name: "MAJENE", type: "Kota" },
    { city_id: 665, city_name: "POLEWALI MANDAR", type: "Kota" },
    { city_id: 687, city_name: "MAMASA", type: "Kota" },
    { city_id: 688, city_name: "MAMUJU UTARA", type: "Kota" }
  ],
  // Sulawesi Tenggara (ID: 20)
  "20": [
    { city_id: 264, city_name: "KENDARI", type: "Kota" },
    { city_id: 267, city_name: "BAU-BAU", type: "Kota" },
    { city_id: 268, city_name: "KOLAKA", type: "Kota" },
    { city_id: 269, city_name: "KOLAKA TIMUR", type: "Kota" },
    { city_id: 271, city_name: "BUTON UTARA", type: "Kota" },
    { city_id: 272, city_name: "MUNA", type: "Kota" },
    { city_id: 273, city_name: "MUNA BARAT", type: "Kota" },
    { city_id: 276, city_name: "KONAWE", type: "Kota" },
    { city_id: 277, city_name: "KONAWE UTARA", type: "Kota" },
    { city_id: 280, city_name: "BOMBANA", type: "Kota" },
    { city_id: 281, city_name: "BUTON", type: "Kota" },
    { city_id: 282, city_name: "BUTON SELATAN", type: "Kota" },
    { city_id: 283, city_name: "BUTON TENGAH", type: "Kota" },
    { city_id: 285, city_name: "KOLAKA UTARA", type: "Kota" },
    { city_id: 286, city_name: "KONAWE SELATAN", type: "Kota" },
    { city_id: 287, city_name: "WAKATOBI", type: "Kota" },
    { city_id: 288, city_name: "KONAWE KEPULAUAN", type: "Kota" }
  ],
  // Sulawesi Utara (ID: 22)
  "22": [
    { city_id: 330, city_name: "MANADO", type: "Kota" },
    { city_id: 331, city_name: "KOTAMOBAGU", type: "Kota" },
    { city_id: 332, city_name: "BOLAANG MONGONDOW UTARA", type: "Kota" },
    { city_id: 333, city_name: "BOLAANG MONGONDOW", type: "Kota" },
    { city_id: 335, city_name: "BOLAANG MONGONDOW SELATAN", type: "Kota" },
    { city_id: 336, city_name: "BOLAANG MONGONDOW TIMUR", type: "Kota" },
    { city_id: 338, city_name: "KEPULAUAN SANGIHE", type: "Kota" },
    { city_id: 339, city_name: "KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)", type: "Kota" },
    { city_id: 341, city_name: "MINAHASA", type: "Kota" },
    { city_id: 342, city_name: "BITUNG", type: "Kota" },
    { city_id: 347, city_name: "KEPULAUAN TALAUD", type: "Kota" },
    { city_id: 348, city_name: "MINAHASA UTARA", type: "Kota" },
    { city_id: 349, city_name: "MINAHASA SELATAN", type: "Kota" },
    { city_id: 351, city_name: "MINAHASA TENGGARA", type: "Kota" },
    { city_id: 352, city_name: "TOMOHON", type: "Kota" }
  ],
  // Sumatra Barat (ID: 23)
  "23": [
    { city_id: 397, city_name: "PADANG", type: "Kota" },
    { city_id: 399, city_name: "TANAH DATAR", type: "Kota" },
    { city_id: 401, city_name: "BUKITTINGGI", type: "Kota" },
    { city_id: 402, city_name: "PASAMAN", type: "Kota" },
    { city_id: 404, city_name: "PESISIR SELATAN", type: "Kota" },
    { city_id: 405, city_name: "PARIAMAN", type: "Kota" },
    { city_id: 406, city_name: "PADANG PARIAMAN", type: "Kota" },
    { city_id: 407, city_name: "LIMA PULUH KOTA", type: "Kota" },
    { city_id: 408, city_name: "PAYAKUMBUH", type: "Kota" },
    { city_id: 410, city_name: "SAWAH LUNTO", type: "Kota" },
    { city_id: 411, city_name: "SOLOK", type: "Kota" },
    { city_id: 412, city_name: "PADANG PANJANG", type: "Kota" },
    { city_id: 413, city_name: "DHARMASRAYA", type: "Kota" },
    { city_id: 416, city_name: "KEPULAUAN MENTAWAI", type: "Kota" },
    { city_id: 419, city_name: "PASAMAN BARAT", type: "Kota" },
    { city_id: 424, city_name: "SOLOK SELATAN", type: "Kota" },
    { city_id: 426, city_name: "SIJUNJUNG", type: "Kota" },
    { city_id: 427, city_name: "AGAM", type: "Kota" }
  ],
  // Sumatra Selatan (ID: 26)
  "26": [
    { city_id: 473, city_name: "PALEMBANG", type: "Kota" },
    { city_id: 475, city_name: "MUSI RAWAS", type: "Kota" },
    { city_id: 476, city_name: "MUSI RAWAS UTARA", type: "Kota" },
    { city_id: 479, city_name: "OGAN KOMERING ULU", type: "Kota" },
    { city_id: 480, city_name: "OGAN KOMERING ILIR", type: "Kota" },
    { city_id: 482, city_name: "LAHAT", type: "Kota" },
    { city_id: 485, city_name: "MUARA ENIM", type: "Kota" },
    { city_id: 486, city_name: "PENUKAL ABAB LEMATANG ILIR", type: "Kota" },
    { city_id: 487, city_name: "PAGAR ALAM", type: "Kota" },
    { city_id: 488, city_name: "PRABUMULIH", type: "Kota" },
    { city_id: 489, city_name: "MUSI BANYUASIN", type: "Kota" },
    { city_id: 491, city_name: "BANYUASIN", type: "Kota" },
    { city_id: 492, city_name: "EMPAT LAWANG", type: "Kota" },
    { city_id: 493, city_name: "OGAN ILIR", type: "Kota" },
    { city_id: 494, city_name: "OGAN KOMERING ULU TIMUR", type: "Kota" },
    { city_id: 495, city_name: "OGAN KOMERING ULU SELATAN", type: "Kota" },
    { city_id: 496, city_name: "LUBUK LINGGAU", type: "Kota" }
  ],
  // Sumatra Utara (ID: 16)
  "16": [
    { city_id: 218, city_name: "TOBA SAMOSIR", type: "Kota" },
    { city_id: 219, city_name: "GUNUNGSITOLI", type: "Kota" },
    { city_id: 220, city_name: "NIAS", type: "Kota" },
    { city_id: 221, city_name: "NIAS BARAT", type: "Kota" },
    { city_id: 222, city_name: "NIAS SELATAN", type: "Kota" },
    { city_id: 223, city_name: "NIAS UTARA", type: "Kota" },
    { city_id: 225, city_name: "SIBOLGA", type: "Kota" },
    { city_id: 226, city_name: "TAPANULI TENGAH", type: "Kota" },
    { city_id: 227, city_name: "PADANG SIDEMPUAN", type: "Kota" },
    { city_id: 228, city_name: "TAPANULI SELATAN", type: "Kota" },
    { city_id: 229, city_name: "TAPANULI UTARA", type: "Kota" },
    { city_id: 231, city_name: "PADANG LAWAS UTARA", type: "Kota" },
    { city_id: 239, city_name: "HUMBANG HASUNDUTAN", type: "Kota" },
    { city_id: 240, city_name: "MANDAILING NATAL", type: "Kota" },
    { city_id: 243, city_name: "PADANG LAWAS", type: "Kota" },
    { city_id: 361, city_name: "MEDAN", type: "Kota" },
    { city_id: 363, city_name: "ASAHAN", type: "Kota" },
    { city_id: 364, city_name: "DAIRI", type: "Kota" },
    { city_id: 365, city_name: "DELI SERDANG", type: "Kota" },
    { city_id: 366, city_name: "BINJAI", type: "Kota" },
    { city_id: 368, city_name: "SIMALUNGUN", type: "Kota" },
    { city_id: 370, city_name: "LABUHANBATU UTARA", type: "Kota" },
    { city_id: 371, city_name: "LABUHANBATU", type: "Kota" },
    { city_id: 372, city_name: "LABUHANBATU SELATAN", type: "Kota" },
    { city_id: 374, city_name: "KARO", type: "Kota" },
    { city_id: 375, city_name: "LANGKAT", type: "Kota" },
    { city_id: 376, city_name: "SERDANG BEDAGAI", type: "Kota" },
    { city_id: 377, city_name: "TEBING TINGGI", type: "Kota" },
    { city_id: 378, city_name: "BATU BARA", type: "Kota" },
    { city_id: 379, city_name: "PAKPAK BHARAT", type: "Kota" },
    { city_id: 380, city_name: "SAMOSIR", type: "Kota" },
    { city_id: 381, city_name: "TANJUNG BALAI", type: "Kota" },
    { city_id: 382, city_name: "PEMATANG SIANTAR", type: "Kota" }
  ],
  // Sulawesi Tengah (ID: 27)
  "27": [
    { city_id: 497, city_name: "PALU", type: "Kota" },
    { city_id: 498, city_name: "BANGGAI", type: "Kota" },
    { city_id: 499, city_name: "POSO", type: "Kota" },
    { city_id: 500, city_name: "TOLI-TOLI", type: "Kota" },
    { city_id: 501, city_name: "BANGGAI LAUT", type: "Kota" },
    { city_id: 502, city_name: "BANGGAI KEPULAUAN", type: "Kota" },
    { city_id: 504, city_name: "BUOL", type: "Kota" },
    { city_id: 505, city_name: "DONGGALA", type: "Kota" },
    { city_id: 507, city_name: "SIGI", type: "Kota" },
    { city_id: 509, city_name: "MOROWALI", type: "Kota" },
    { city_id: 510, city_name: "MOROWALI UTARA", type: "Kota" },
    { city_id: 511, city_name: "PARIGI MOUTONG", type: "Kota" },
    { city_id: 512, city_name: "TOJO UNA-UNA", type: "Kota" }
  ],
  // Kalimantan Barat (ID: 28)
  "28": [
    { city_id: 513, city_name: "PONTIANAK", type: "Kota" },
    { city_id: 514, city_name: "KETAPANG", type: "Kota" },
    { city_id: 515, city_name: "SANGGAU", type: "Kota" },
    { city_id: 516, city_name: "SINGKAWANG", type: "Kota" },
    { city_id: 517, city_name: "SINTANG", type: "Kota" },
    { city_id: 519, city_name: "KAPUAS HULU", type: "Kota" },
    { city_id: 522, city_name: "BENGKAYANG", type: "Kota" },
    { city_id: 523, city_name: "LANDAK", type: "Kota" },
    { city_id: 524, city_name: "MELAWI", type: "Kota" },
    { city_id: 526, city_name: "MEMPAWAH", type: "Kota" },
    { city_id: 527, city_name: "KUBU RAYA", type: "Kota" },
    { city_id: 528, city_name: "SAMBAS", type: "Kota" },
    { city_id: 529, city_name: "SEKADAU", type: "Kota" },
    { city_id: 530, city_name: "KAYONG UTARA", type: "Kota" }
  ],
  // Papua Barat (ID: 29)
  "29": [
    { city_id: 546, city_name: "SORONG", type: "Kota" },
    { city_id: 547, city_name: "TAMBRAUW", type: "Kota" },
    { city_id: 548, city_name: "FAKFAK", type: "Kota" },
    { city_id: 549, city_name: "KAIMANA", type: "Kota" },
    { city_id: 551, city_name: "RAJA AMPAT", type: "Kota" },
    { city_id: 552, city_name: "SORONG SELATAN", type: "Kota" },
    { city_id: 553, city_name: "MAYBRAT", type: "Kota" },
    { city_id: 554, city_name: "TELUK BINTUNI", type: "Kota" },
    { city_id: 556, city_name: "TELUK WONDAMA", type: "Kota" },
    { city_id: 557, city_name: "MANOKWARI", type: "Kota" },
    { city_id: 558, city_name: "PEGUNUNGAN ARFAK", type: "Kota" },
    { city_id: 559, city_name: "MANOKWARI SELATAN", type: "Kota" }
  ],
  // Lampung (ID: 30) - Partial based on visible data
  "30": [
    { city_id: 598, city_name: "BANDAR LAMPUNG", type: "Kota" },
    { city_id: 599, city_name: "LAMPUNG SELATAN", type: "Kota" },
    { city_id: 600, city_name: "LAMPUNG UTARA", type: "Kota" },
    { city_id: 601, city_name: "METRO", type: "Kota" },
    { city_id: 603, city_name: "LAMPUNG BARAT", type: "Kota" },
    { city_id: 604, city_name: "PESISIR BARAT", type: "Kota" }
  ],
  // Kalimantan Utara (ID: 31)
  "31": [
    { city_id: 626, city_name: "TARAKAN", type: "Kota" },
    { city_id: 627, city_name: "BULUNGAN", type: "Kota" },
    { city_id: 628, city_name: "MALINAU", type: "Kota" },
    { city_id: 629, city_name: "NUNUKAN", type: "Kota" },
    { city_id: 631, city_name: "TANA TIDUNG", type: "Kota" }
  ],
  // Maluku Utara (ID: 32)
  "32": [
    { city_id: 636, city_name: "TERNATE", type: "Kota" },
    { city_id: 637, city_name: "HALMAHERA BARAT", type: "Kota" },
    { city_id: 639, city_name: "HALMAHERA SELATAN", type: "Kota" },
    { city_id: 640, city_name: "HALMAHERA TENGAH", type: "Kota" },
    { city_id: 641, city_name: "HALMAHERA TIMUR", type: "Kota" },
    { city_id: 642, city_name: "HALMAHERA UTARA", type: "Kota" },
    { city_id: 643, city_name: "PULAU MOROTAI", type: "Kota" },
    { city_id: 644, city_name: "KEPULAUAN SULA", type: "Kota" },
    { city_id: 646, city_name: "PULAU TALIABU", type: "Kota" },
    { city_id: 647, city_name: "TIDORE KEPULAUAN", type: "Kota" }
  ],
  // Sulawesi Selatan (ID: 33)
  "33": [
    { city_id: 648, city_name: "MAKASSAR", type: "Kota" },
    { city_id: 649, city_name: "BANTAENG", type: "Kota" },
    { city_id: 650, city_name: "BARRU", type: "Kota" },
    { city_id: 651, city_name: "BULUKUMBA", type: "Kota" },
    { city_id: 652, city_name: "ENREKANG", type: "Kota" },
    { city_id: 653, city_name: "JENEPONTO", type: "Kota" },
    { city_id: 654, city_name: "TANA TORAJA", type: "Kota" },
    { city_id: 655, city_name: "TORAJA UTARA", type: "Kota" },
    { city_id: 659, city_name: "MAROS", type: "Kota" },
    { city_id: 663, city_name: "PALOPO", type: "Kota" },
    { city_id: 664, city_name: "PINRANG", type: "Kota" },
    { city_id: 667, city_name: "SIDENRENG RAPPANG", type: "Kota" },
    { city_id: 670, city_name: "WAJO", type: "Kota" },
    { city_id: 671, city_name: "SINJAI", type: "Kota" },
    { city_id: 673, city_name: "GOWA", type: "Kota" },
    { city_id: 674, city_name: "TAKALAR", type: "Kota" },
    { city_id: 676, city_name: "BONE", type: "Kota" },
    { city_id: 678, city_name: "SOPPENG", type: "Kota" },
    { city_id: 679, city_name: "KEPULAUAN SELAYAR", type: "Kota" },
    { city_id: 680, city_name: "PANGKAJENE KEPULAUAN", type: "Kota" },
    { city_id: 683, city_name: "PAREPARE", type: "Kota" },
    { city_id: 684, city_name: "LUWU", type: "Kota" },
    { city_id: 685, city_name: "LUWU TIMUR", type: "Kota" },
    { city_id: 686, city_name: "LUWU UTARA", type: "Kota" }
  ],
  // DKI Jakarta (ID: 10)
  "10": [
    { city_id: 135, city_name: "JAKARTA BARAT", type: "Kota" },
    { city_id: 136, city_name: "JAKARTA SELATAN", type: "Kota" },
    { city_id: 137, city_name: "JAKARTA PUSAT", type: "Kota" },
    { city_id: 138, city_name: "JAKARTA UTARA", type: "Kota" },
    { city_id: 139, city_name: "JAKARTA TIMUR", type: "Kota" },
    { city_id: 141, city_name: "KEPULAUAN SERIBU", type: "Kota" }
  ]
};
